import type { ColorFormatDef } from '../lib/types';

// v7 and v8 share the same lv_img_dsc_t struct shape and CF_* macro family;
// v8 additionally adds RGB565A8 (see v8.ts).
export const V7_FORMATS: ColorFormatDef[] = [
  {
    id: 'true_color',
    label: 'True color',
    macro: 'LV_IMG_CF_TRUE_COLOR',
    category: 'trueColor',
    bpp: 16,
    supportsAlpha: false,
    supportsChroma: false,
  },
  {
    id: 'true_color_alpha',
    label: 'True color + alpha',
    macro: 'LV_IMG_CF_TRUE_COLOR_ALPHA',
    category: 'trueColor',
    bpp: 16,
    supportsAlpha: true,
    supportsChroma: false,
  },
  {
    id: 'true_color_chroma',
    label: 'True color + chroma key',
    macro: 'LV_IMG_CF_TRUE_COLOR_CHROMA',
    category: 'trueColor',
    bpp: 16,
    supportsAlpha: false,
    supportsChroma: true,
  },
  {
    id: 'indexed_1bit',
    label: 'Indexed 1-bit (2 colors)',
    macro: 'LV_IMG_CF_INDEXED_1BIT',
    category: 'indexed',
    bpp: 1,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 2,
  },
  {
    id: 'indexed_2bit',
    label: 'Indexed 2-bit (4 colors)',
    macro: 'LV_IMG_CF_INDEXED_2BIT',
    category: 'indexed',
    bpp: 2,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 4,
  },
  {
    id: 'indexed_4bit',
    label: 'Indexed 4-bit (16 colors)',
    macro: 'LV_IMG_CF_INDEXED_4BIT',
    category: 'indexed',
    bpp: 4,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 16,
  },
  {
    id: 'indexed_8bit',
    label: 'Indexed 8-bit (256 colors)',
    macro: 'LV_IMG_CF_INDEXED_8BIT',
    category: 'indexed',
    bpp: 8,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 256,
  },
  {
    id: 'alpha_1bit',
    label: 'Alpha-only 1-bit',
    macro: 'LV_IMG_CF_ALPHA_1BIT',
    category: 'alpha',
    bpp: 1,
    supportsAlpha: true,
    supportsChroma: false,
  },
  {
    id: 'alpha_2bit',
    label: 'Alpha-only 2-bit',
    macro: 'LV_IMG_CF_ALPHA_2BIT',
    category: 'alpha',
    bpp: 2,
    supportsAlpha: true,
    supportsChroma: false,
  },
  {
    id: 'alpha_4bit',
    label: 'Alpha-only 4-bit',
    macro: 'LV_IMG_CF_ALPHA_4BIT',
    category: 'alpha',
    bpp: 4,
    supportsAlpha: true,
    supportsChroma: false,
  },
  {
    id: 'alpha_8bit',
    label: 'Alpha-only 8-bit',
    macro: 'LV_IMG_CF_ALPHA_8BIT',
    category: 'alpha',
    bpp: 8,
    supportsAlpha: true,
    supportsChroma: false,
  },
  {
    id: 'raw',
    label: 'Raw (passthrough, app-decoded)',
    macro: 'LV_IMG_CF_RAW',
    category: 'raw',
    bpp: 0,
    supportsAlpha: false,
    supportsChroma: false,
    isRawPassthrough: true,
  },
  {
    id: 'raw_alpha',
    label: 'Raw + alpha (passthrough, app-decoded)',
    macro: 'LV_IMG_CF_RAW_ALPHA',
    category: 'raw',
    bpp: 0,
    supportsAlpha: true,
    supportsChroma: false,
    isRawPassthrough: true,
  },
  {
    id: 'raw_chroma',
    label: 'Raw + chroma key (passthrough, app-decoded)',
    macro: 'LV_IMG_CF_RAW_CHROMA',
    category: 'raw',
    bpp: 0,
    supportsAlpha: false,
    supportsChroma: true,
    isRawPassthrough: true,
  },
];
