import type { ColorFormatDef } from '../lib/types';

// v9 replaced lv_img_cf_t with LV_COLOR_FORMAT_* (lv_color_format_t) and lv_img_dsc_t
// with lv_image_dsc_t (see encodeCArray.ts for the struct shape difference).
export const V9_FORMATS: ColorFormatDef[] = [
  {
    id: 'rgb565',
    label: 'RGB565',
    macro: 'LV_COLOR_FORMAT_RGB565',
    category: 'trueColor',
    bpp: 16,
    supportsAlpha: false,
    supportsChroma: true,
    supportsRle: true,
  },
  {
    id: 'rgb888',
    label: 'RGB888',
    macro: 'LV_COLOR_FORMAT_RGB888',
    category: 'trueColor',
    bpp: 24,
    supportsAlpha: false,
    supportsChroma: true,
    supportsRle: true,
  },
  {
    id: 'argb8888',
    label: 'ARGB8888',
    macro: 'LV_COLOR_FORMAT_ARGB8888',
    category: 'trueColor',
    bpp: 32,
    supportsAlpha: true,
    supportsChroma: false,
    supportsRle: true,
  },
  {
    id: 'xrgb8888',
    label: 'XRGB8888',
    macro: 'LV_COLOR_FORMAT_XRGB8888',
    category: 'trueColor',
    bpp: 32,
    supportsAlpha: false,
    supportsChroma: false,
    supportsRle: true,
  },
  {
    id: 'indexed_1bit',
    label: 'Indexed 1-bit (2 colors)',
    macro: 'LV_COLOR_FORMAT_I1',
    category: 'indexed',
    bpp: 1,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 2,
    supportsRle: true,
  },
  {
    id: 'indexed_2bit',
    label: 'Indexed 2-bit (4 colors)',
    macro: 'LV_COLOR_FORMAT_I2',
    category: 'indexed',
    bpp: 2,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 4,
    supportsRle: true,
  },
  {
    id: 'indexed_4bit',
    label: 'Indexed 4-bit (16 colors)',
    macro: 'LV_COLOR_FORMAT_I4',
    category: 'indexed',
    bpp: 4,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 16,
    supportsRle: true,
  },
  {
    id: 'indexed_8bit',
    label: 'Indexed 8-bit (256 colors)',
    macro: 'LV_COLOR_FORMAT_I8',
    category: 'indexed',
    bpp: 8,
    supportsAlpha: true,
    supportsChroma: false,
    paletteSize: 256,
    supportsRle: true,
  },
  {
    id: 'l8',
    label: 'L8 (grayscale, no alpha)',
    macro: 'LV_COLOR_FORMAT_L8',
    category: 'grayscale',
    bpp: 8,
    supportsAlpha: false,
    supportsChroma: false,
    supportsRle: true,
  },
  {
    id: 'a8',
    label: 'Alpha-only (A8)',
    macro: 'LV_COLOR_FORMAT_A8',
    category: 'alpha',
    bpp: 8,
    supportsAlpha: true,
    supportsChroma: false,
    supportsRle: true,
  },
];
